schema_version: 1

context:
  name: islp
  version: "0.4.0"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/islp-${{ version }}.tar.gz
  sha256: 675792d4406c7c09f4e3bb132232b27f7de00e953cc477bc273f7971e03f9d36

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - versioneer
    - sphinx >=1.0
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.7.1
    - scipy >=0.9
    - pandas >=0.20
    - lxml
    - scikit-learn >=1.2
    - joblib
    - statsmodels >=0.13
    - lifelines
    - pygam
    - pytorch
    - pytorch-lightning
    - torchmetrics

tests:
  - python:
      imports:
        - ISLP
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - pip check

about:
  summary: Library for ISLP labs
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://www.statlearning.com/
  repository: https://github.com/intro-stat-learning/ISLP
  documentation: https://intro-stat-learning.github.io/ISLP/labs.html

extra:
  recipe-maintainers:
    - mendible
